server:
  port: 8989
  servlet:
    context-path: /book
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
    date-format: yyyy-MM-dd
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd
mybatis:
  type-aliases-package: com.baizhi.entity
logging:
  level:
    root: error
    com.baizhi.aspect: debug